# Generated by Django 4.2.9 on 2024-01-27 02:33

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, unique=True)),
                ('body', tinymce.models.HTMLField()),
                ('posted', models.BooleanField(default=False)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, blank=True, default=None, editable=False, null=True, populate_from='topic', unique_with=['author'])),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'articles',
                'ordering': ('-id', 'updated_on'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('total_post', models.IntegerField(default=0, verbose_name='total posts')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('-total_post',),
            },
        ),
    ]
