# Generated by Django 5.0 on 2023-12-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='total_post',
            field=models.IntegerField(default=0, verbose_name='total posts'),
        ),
    ]
