# Generated by Django 4.2.9 on 2024-01-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
