# Generated by Django 5.0 on 2023-12-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_total_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_on',
        ),
        migrations.AddField(
            model_name='article',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
