# Generated by Django 4.2.9 on 2024-02-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-total_post', '-id'), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(blank=True, default='media/profile/default.jpg', max_length=500, null=True, upload_to=''),
        ),
    ]
